### ISSUE TITLE
feat: C# Testing Library

### ISSUE THREAD

**Issue by GuyWhoCode** [Northrop-Grumman-Collaboration-Project/progress-board-tracker#28]
We need to have consistent dummy data to ensure that the database operations we perform work. This will also be used for unit tests and hopefully integration tests in the future.

**Comment by marked01one** [comment]
I have a .NET project that have a dummy data generator called during server startup. Check it if you need reference.
https://github.com/marked01one/save-the-date-dotnet/blob/main/API/Program.cs
