### ISSUE TITLE
download and render openstreetmap

### ISSUE THREAD

**Issue by Priyatham-sai-chand** [Northrop-Grumman-Collaboration-Project/progress-board-tracker#53]
Download the data for Cal Poly Pomona
- [x] store it somewhere
- [x] Try to render the map as component in Vue Repo

**Comment by Leaversa** [comment]
Following the guide from https://github.com/Overv/openstreetmap-tile-server

We can use a docker container to run a OpenStreetMap server.
For the sake of testing fetch only Southern California osm data from https://download.geofabrik.de/north-america/us/california/socal.html

By default tiles will be hosted at `http://localhost:8080/tile/{z}/{x}/{y}.png`

**Comment by Priyatham-sai-chand** [comment]
That's great ! do you think you can please put the command in a docker-compose.yml file  ?
Any other preference ?

**Comment by Leaversa** [comment]
I think considering its a single image docker-compose isn't necessary. I can try to look into building a dockerfile that simplifies the commands or create shell scripts to make it easier to run.

**Comment by Priyatham-sai-chand** [comment]
If that's the case, We may not need the dockerfile too.

We just write the commands properly in the docs.
